FROM node:18-alpine

WORKDIR /app

# Clean npm cache and install dependencies
COPY package*.json ./
RUN npm cache clean --force && \
    npm install && \
    npm install --save-dev \
    @babel/plugin-proposal-private-property-in-object \
    @babel/plugin-transform-private-property-in-object \
    eslint-plugin-unused-imports

# Copy source code
COPY . .

# Start app in development mode
CMD ["npm", "start"]
