services:
  app:
    build:
      context: .
      target: app
    container_name: shh-app
    privileged: true
    network_mode: host
    ports:
      - "3000:3000"
      - "1514:1514"
      - "9090:9090"
    environment:
      # Build Configuration
      - DOCKER_BUILD=1
      - NODE_OPTIONS=--max-old-space-size=4096
      - SKIP_PREFLIGHT_CHECK=true
      - DISABLE_ESLINT_PLUGIN=true

      # Server
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - HOST=0.0.0.0
      - MAX_REQUEST_SIZE=10485760

      # Database
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=shh

      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

      # Authentication
      - DISABLE_AUTH=${DISABLE_AUTH:-false}
      - REACT_APP_DISABLE_AUTH=${REACT_APP_DISABLE_AUTH:-false}

      # JWT
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - JWT_EXPIRY=1h
      - JWT_REFRESH_EXPIRY=7d

      # CORS
      - CORS_ORIGIN=http://localhost:3000
      - CORS_METHODS=GET,HEAD,PUT,PATCH,POST,DELETE
      - CORS_ALLOWED_HEADERS=Content-Type,Authorization
      - CORS_EXPOSED_HEADERS=
      - CORS_CREDENTIALS=true
      - CORS_MAX_AGE=86400

      # Rate Limiting
      - RATE_LIMIT_WINDOW=900000
      - RATE_LIMIT_MAX=100

      # Security
      - MAX_FILE_SIZE=52428800

      # OpenAI (optional)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=gpt-4
      - OPENAI_ORG=${OPENAI_ORG:-}
      - OPENAI_MAX_TOKENS=2000
      - OPENAI_TEMPERATURE=0.7

      # OpenRouter (optional)
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - OPENROUTER_MODEL=anthropic/claude-2
      - OPENROUTER_BASE_URL=https://openrouter.ai/api/v1/chat/completions
      - OPENROUTER_MAX_TOKENS=2000
      - OPENROUTER_TEMPERATURE=0.7

      # Logging
      - LOG_LEVEL=info
      - LOG_FILE=/var/log/shh/app.log

      # Gotify (optional)
      - GOTIFY_URL=${GOTIFY_URL:-}
      - GOTIFY_TOKEN=${GOTIFY_TOKEN:-}

      # Prometheus
      - PROMETHEUS_PORT=9090
    volumes:
      - ${SHH_DATA_DIR:-/var/lib/shh}/logs:/var/log/shh
      - ${SHH_DATA_DIR:-/var/lib/shh}/data:/var/lib/shh
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: shh-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shh
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: shh-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
