[supervisord]
nodaemon=true
user=nobody
logfile=/app/logs/supervisord.log
pidfile=/app/run/supervisord.pid

[program:gunicorn]
command=gunicorn --config gunicorn.conf.py wsgi:app
directory=/app
user=nobody
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/logs/gunicorn.log

[program:watcher]
command=python watcher.py
directory=/app
user=nobody
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/logs/watcher.log

[supervisorctl]
serverurl=unix:///app/run/supervisor.sock

[unix_http_server]
file=/app/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
