global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alerting rules
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

# Rule files
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Application metrics
  - job_name: 'app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:4000', 'app:3000']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Docker daemon metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']

# Additional configuration for service discovery
# Uncomment and configure if using Kubernetes or dynamic service discovery
# kubernetes_sd_configs:
#   - role: service
#     api_server: https://kubernetes.default.svc
#     tls_config:
#       ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
